<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_AVANAR</name>
   <tag></tag>
   <elementGuidId>2b650740-24ea-4e70-ae9c-f82d00995715</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#avancarintro</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='avancarintro']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>691efa67-d13a-406e-871d-0db11c5ceacc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>avancarintro</value>
      <webElementGuid>f6b8e677-45d5-4e8d-a02d-96a42e0f91f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:idfpout();</value>
      <webElementGuid>b1ea35f8-c694-49f3-b141-18a427dbe49f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>0c090e4a-07b2-4751-a66b-c7401fc073af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>idfpimg</value>
      <webElementGuid>09ee2d2f-bdc0-4701-afc2-504a9c84aafa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AVANÇAR</value>
      <webElementGuid>f46db929-f4d8-451b-911b-35efb2e1ecb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;avancarintro&quot;)</value>
      <webElementGuid>0637997a-8935-412f-ae8e-734c70e6ef25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Record Tudo sobre desporto. Futebol, m_9c6716/iframe_google_ads_iframe_4196RECORD_WEBSITE_7c01d3</value>
      <webElementGuid>67509b6c-6ddf-4c97-b08f-3e012f016818</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='avancarintro']</value>
      <webElementGuid>7d276d3f-8eb6-4ee7-b476-d400c6236cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idfpheader']/div/a</value>
      <webElementGuid>414ce0c6-c1dd-4dc4-b736-29ebfbd45ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'AVANÇAR')]</value>
      <webElementGuid>22d490ab-be25-41cb-a6bb-8c508b9c35d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:idfpout();')]</value>
      <webElementGuid>84eee64d-3718-4b4f-b250-6a2ead8db500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>dd7b0fdd-d281-4a47-b862-8fc3d28b9990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'avancarintro' and @href = 'javascript:idfpout();' and (text() = 'AVANÇAR' or . = 'AVANÇAR')]</value>
      <webElementGuid>a594d31b-c1c5-404d-843d-b67701528744</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
