<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Benfica</name>
   <tag></tag>
   <elementGuidId>4e7adec3-9ca9-45a4-99da-d20dc87a3cb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.nav-link.eventAnalytics.benfica</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Benfica')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9b2553da-2379-441d-ae0e-54a2606db8fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link eventAnalytics benfica</value>
      <webElementGuid>0bd99a59-b21d-4b35-b489-02dc9c91909a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics-action</name>
      <type>Main</type>
      <value>REF_2</value>
      <webElementGuid>927c5011-bcaf-4179-95df-9b1d8fd33ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics-label</name>
      <type>Main</type>
      <value>/futebol/futebol-nacional/liga-bwin/benfica?ref=Masterpage_MenuDestaque</value>
      <webElementGuid>42dbbc55-19c2-443a-a859-bd735e6e64d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-category</name>
      <type>Main</type>
      <value>Geral</value>
      <webElementGuid>4afe0411-d93b-4663-bede-9e01f07f0661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>MenuBarra</value>
      <webElementGuid>a49761f4-056b-4f53-a7c3-5cdc7f9957f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-consumer</name>
      <type>Main</type>
      <value>ga,piwik</value>
      <webElementGuid>b25c9fc9-6ce5-4bab-b98a-9cb90920f2e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-areaid</name>
      <type>Main</type>
      <value>81</value>
      <webElementGuid>b60b323c-e7e9-4945-9576-e9359aee27c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/futebol/futebol-nacional/liga-bwin/benfica?ref=Masterpage_MenuDestaque</value>
      <webElementGuid>4e2758de-4f21-44fb-a237-94bf7873ef20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wbo-id</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>447ddc6e-d996-40b3-a257-eeb818bcfe13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Benfica</value>
      <webElementGuid>5f68f56f-0085-48d2-b05c-8d852c6e0f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/header[@class=&quot;header&quot;]/div[@class=&quot;hideHeader&quot;]/section[@class=&quot;canais_topo&quot;]/div[@class=&quot;container&quot;]/nav[@class=&quot;nav&quot;]/a[@class=&quot;nav-link eventAnalytics benfica&quot;]</value>
      <webElementGuid>6c3569fe-7eb5-45ef-82b2-9ee4501cbbc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Benfica')]</value>
      <webElementGuid>a28fc4fd-b568-4c3f-9b59-347827310235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/futebol/futebol-nacional/liga-bwin/benfica?ref=Masterpage_MenuDestaque')]</value>
      <webElementGuid>cfba3911-5e46-4e66-abe5-cd60649b0c64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>0c794de3-4c06-4e40-b9b3-091ba1890c4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/futebol/futebol-nacional/liga-bwin/benfica?ref=Masterpage_MenuDestaque' and (text() = 'Benfica' or . = 'Benfica')]</value>
      <webElementGuid>1eb1167d-0525-4821-a590-66756f7302df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
