<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Benfica</name>
   <tag></tag>
   <elementGuidId>4e7adec3-9ca9-45a4-99da-d20dc87a3cb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.nav-link.eventAnalytics.benfica</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Benfica')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7dabbc2e-f8ab-425c-812c-f963c3a281c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link eventAnalytics benfica</value>
      <webElementGuid>4d195f49-756f-4691-8245-158e9a3dac74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics-action</name>
      <type>Main</type>
      <value>REF_4</value>
      <webElementGuid>26822646-aeee-4d49-a045-fe23f95bf8cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics-label</name>
      <type>Main</type>
      <value>/futebol/futebol-nacional/liga-bwin/benfica?ref=Masterpage_MenuDestaque</value>
      <webElementGuid>4432c5fa-8404-40df-8567-5b4aeb57b9f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-category</name>
      <type>Main</type>
      <value>Geral</value>
      <webElementGuid>02cd04aa-a52c-4e3e-920e-4e2159251fe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>MenuBarra</value>
      <webElementGuid>3ff09701-396e-4995-a702-fe9874359f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-consumer</name>
      <type>Main</type>
      <value>ga,piwik</value>
      <webElementGuid>d664da7d-6209-4fcf-97d2-25f934177f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-areaid</name>
      <type>Main</type>
      <value>81</value>
      <webElementGuid>8715f72e-13e4-415e-b427-ae1fe16f2c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/futebol/futebol-nacional/liga-bwin/benfica?ref=Masterpage_MenuDestaque</value>
      <webElementGuid>2abfb9e6-e83a-4009-bda9-0751224746c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wbo-id</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>8365a1a0-b60b-4eca-a085-d8378dc40ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Benfica</value>
      <webElementGuid>ab12b2d0-e717-4e16-9097-d61065929749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/header[@class=&quot;header&quot;]/div[@class=&quot;hideHeader&quot;]/section[@class=&quot;canais_topo&quot;]/div[@class=&quot;container&quot;]/nav[@class=&quot;nav&quot;]/a[@class=&quot;nav-link eventAnalytics benfica&quot;]</value>
      <webElementGuid>3ed521f3-4d4b-4c32-99c7-6f37b4386d75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Benfica')]</value>
      <webElementGuid>b9ca0630-2a50-4b60-b5ba-601cc9e940fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sporting'])[1]/following::a[1]</value>
      <webElementGuid>518e9853-c7b9-4a0b-a0b8-fdfd7e71d214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FC Porto'])[1]/preceding::a[1]</value>
      <webElementGuid>48b027ee-95da-41a7-8fe8-925e7e4fa8b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mercado'])[1]/preceding::a[2]</value>
      <webElementGuid>ef6154d9-ed49-427d-b0e4-5bd2551b7732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Benfica']/parent::*</value>
      <webElementGuid>af78be69-6d75-4f14-9315-f52de7d38ce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/futebol/futebol-nacional/liga-bwin/benfica?ref=Masterpage_MenuDestaque')]</value>
      <webElementGuid>69ef0e43-bd38-48b7-b7db-4ccdbc4f6d42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]</value>
      <webElementGuid>722671d1-6d51-4c65-9742-7cc02f4fefc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/futebol/futebol-nacional/liga-bwin/benfica?ref=Masterpage_MenuDestaque' and (text() = 'Benfica' or . = 'Benfica')]</value>
      <webElementGuid>669ee36c-e241-4d0f-8307-b0c67b714442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>0c794de3-4c06-4e40-b9b3-091ba1890c4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
