<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cancelar</name>
   <tag></tag>
   <elementGuidId>99ef5019-f39f-4fe1-b9b5-1529fd5f3653</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cancelar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cancelar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ba81e8cd-13f0-447d-8ec2-43f45119b2c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>bcb5e9da-bec5-468b-8b4e-53cc5d846c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cancelar</value>
      <webElementGuid>ab3cd1be-8c9c-4308-aa30-a0d30ff81c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cancelar pushCancelRegister btClose_notificacoes</value>
      <webElementGuid>f6719438-7d7e-41ed-858b-d1d2d42ff76c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>subscribe</value>
      <webElementGuid>681c622c-f8f6-4551-8294-0b14703c799e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wbo-id</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>5329ce0e-59f8-4dcb-a4c2-397a9aca9ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancelar</value>
      <webElementGuid>4cdde4b1-a383-418e-a7d6-343bf97bf994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cancelar&quot;)</value>
      <webElementGuid>5383321f-5896-42eb-98fd-313156953b0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cancelar']</value>
      <webElementGuid>08ac66ef-3472-4aa1-9d95-8492efda28d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='notificacao']/div/div[2]/a</value>
      <webElementGuid>4582fad4-b6ee-45aa-9ecf-1fb42914b663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cancelar')]</value>
      <webElementGuid>539ab501-7b98-4705-a88d-6bd477fd94be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0)')]</value>
      <webElementGuid>285ac01d-ce18-4c35-b265-8898aadb9588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div/div[2]/a</value>
      <webElementGuid>736f6724-017f-4371-ad34-5716e1bd23bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @id = 'cancelar' and (text() = 'Cancelar' or . = 'Cancelar')]</value>
      <webElementGuid>d8ac8833-1927-43c4-8e04-5de98387116a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
