<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Perfil Colaborador Intranet</name>
   <tag></tag>
   <elementGuidId>1eaf2ec8-2620-47f4-ab87-2d56b13f9ba2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.text-primary > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b4-b5-b1-Menu']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>858ebb63-3a14-4502-9538-860fb0745fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Perfil Colaborador Intranet</value>
      <webElementGuid>a6357e47-ef8b-4eb5-9d31-c302c3e873b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b4-b5-b1-Menu&quot;)/div[@class=&quot;text-primary&quot;]/span[1]</value>
      <webElementGuid>94f8a2db-d154-43c6-ba7d-6978d71f3069</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b4-b5-b1-Menu']/div/span</value>
      <webElementGuid>77ee8cdb-d9d2-43f4-b5ef-ab159d511ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/span</value>
      <webElementGuid>b0906da6-2d22-41ed-9136-100f82bed5f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Perfil Colaborador Intranet' or . = 'Perfil Colaborador Intranet')]</value>
      <webElementGuid>dc9b18b1-12e1-47df-a416-ff7c450f4a47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
