<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputInput_UserEmail</name>
   <tag></tag>
   <elementGuidId>11b1d474-15f7-483b-ad53-14dba5941029</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Input_UserEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Input_UserEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>285765bc-2044-48ce-966d-9d887209139c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>0d821723-9e78-4746-955b-e574b47d0360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>6042f6cd-5e26-4f77-a8ee-11d8277bb47c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>40a42fb0-3ee6-4eef-8ea7-b8ad53f63640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>21c9fd8f-a99b-42ca-959a-1d877290e85a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Input_UserEmail</value>
      <webElementGuid>a3a316ad-7e18-4210-8467-dcf692bb416f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Input_UserEmail&quot;)</value>
      <webElementGuid>92013311-ee6c-4df5-8289-7483129ad9ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Input_UserEmail']</value>
      <webElementGuid>60b95470-7165-47b7-a4bd-bcb6f42bf6a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-Input']/span/input</value>
      <webElementGuid>eb87ed30-6d72-4714-bc2d-9857afab05c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>98394bb3-b3bc-4adf-aef8-89c2f2260326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'Input_UserEmail']</value>
      <webElementGuid>13dd5c00-54fe-4f1c-bd9d-a0036aa217e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
