<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Aceitar e fechar</name>
   <tag></tag>
   <elementGuidId>56e140a6-a851-4890-b4db-9b64868f6d96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#didomi-notice-agree-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='didomi-notice-agree-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8ed4f46d-e1b3-4828-b827-169e378477a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>didomi-notice-agree-button</value>
      <webElementGuid>eacf17fa-e1be-470a-a939-9a162f69a7b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>didomi-components-button didomi-button didomi-dismiss-button didomi-components-button--color didomi-button-highlight highlight-button</value>
      <webElementGuid>d52355ab-1c96-40d4-90fb-6836231296d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Aceitar e fechar: Aceitar o nosso processamento de dados e fechar</value>
      <webElementGuid>69eb1de2-2b9a-4dd0-a2dd-9067f81586ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aceitar e fechar</value>
      <webElementGuid>14f90fdb-9264-45c9-8d9f-b24b8a684071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;didomi-notice-agree-button&quot;)</value>
      <webElementGuid>c6414843-4c3e-4daa-960a-153a209b33c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='didomi-notice-agree-button']</value>
      <webElementGuid>bba53562-00e0-4b35-8ef2-388830e9ead4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='buttons']/button[2]</value>
      <webElementGuid>3e84945f-e16b-4180-bdd9-91cb1971387f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>6fe4caea-4a95-4486-8790-5373f1470acb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'didomi-notice-agree-button' and (text() = 'Aceitar e fechar' or . = 'Aceitar e fechar')]</value>
      <webElementGuid>1d82ff27-e693-473d-82f3-ded70eff252a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
