<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>74310177-bc73-488c-a808-f2024a830ea1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.g-logo.logo.main-logo > a > img[alt=&quot;Expresso&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/header/div/div/div[2]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>86245b3d-10fe-4b9f-80c6-867257d73cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fetchpriority</name>
      <type>Main</type>
      <value>low</value>
      <webElementGuid>7b077558-bc13-43ef-b567-0ad271cba0c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://sdistribution.impresa.pt/data/content/binaries/381/fe3/ca029610-137e-495e-a9c4-eef35023d8a3/logo-expresso-50.svg</value>
      <webElementGuid>5ff620d4-5171-4644-9557-6fe38e16dcc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Expresso</value>
      <webElementGuid>eb96124d-0ca0-4910-ad52-ab0c4ee4c22d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/header[@class=&quot;main-header&quot;]/div[@class=&quot;main-header-inner&quot;]/div[@class=&quot;main-header-container row row-1 row-1-3 row-odd row-first&quot;]/div[@class=&quot;g-logo logo main-logo&quot;]/a[1]/img[1]</value>
      <webElementGuid>aba11c82-cfaa-4bdf-948c-1106bf3352e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/header/div/div/div[2]/a/img</value>
      <webElementGuid>c6051146-ccd0-45d8-98c4-eee6e013751b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Expresso'])[2]</value>
      <webElementGuid>2bac39f8-21f3-478b-a8d3-186db7474aea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/img</value>
      <webElementGuid>4c56b7b3-a4c8-4162-ae67-6c4ae46a198e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://sdistribution.impresa.pt/data/content/binaries/381/fe3/ca029610-137e-495e-a9c4-eef35023d8a3/logo-expresso-50.svg' and @alt = 'Expresso']</value>
      <webElementGuid>0cc5d73a-1f81-4230-9a3f-cbb9c8eec834</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
