<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>7fdd9401-8a6b-4a43-9c0b-55a477199663</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Presidente&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='WebPartWPQ2']/div/div/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a30c26ad-fd82-468a-bc82-e6264a39bef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Presidente</value>
      <webElementGuid>a109f460-a371-49a6-a97b-7fa54bd42eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/sites/PARXVL/PublishingImages/home-page/PARPresidente_ASSilva-HP.png</value>
      <webElementGuid>3a130261-70ec-4558-be43-2c466710bfea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WebPartWPQ2&quot;)/div[@class=&quot;ms-rtestate-field&quot;]/div[@class=&quot;ms-dialogHidden&quot;]/div[@class=&quot;row page-row-wrapper&quot;]/div[@class=&quot;col-sm-12 col-md-4 left-block ImageBlock&quot;]/a[1]/img[1]</value>
      <webElementGuid>d0cea59c-5a83-4530-8164-618ca9d394b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='WebPartWPQ2']/div/div/div/div/a/img</value>
      <webElementGuid>1bb69195-0380-48c6-96c5-9d9932defd7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Presidente']</value>
      <webElementGuid>2d5b56d4-66dd-4697-8c2b-2c1670e9a7a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/a/img</value>
      <webElementGuid>ca11e5ce-3ece-4398-b914-5f8754e6bfb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Presidente' and @src = '/sites/PARXVL/PublishingImages/home-page/PARPresidente_ASSilva-HP.png']</value>
      <webElementGuid>cc7ff87a-0fb2-42ec-a9aa-19d1095fe8e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
