<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Consentir</name>
   <tag></tag>
   <elementGuidId>64d09b11-576a-4ef9-9a11-61a21eeac0f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.fc-button-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>2ce16aaf-d56a-410a-917c-9ca78b1704d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fc-button-label</value>
      <webElementGuid>72945d31-f927-4e70-90f1-0bdd9a69e9c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Consentir</value>
      <webElementGuid>241ce1d2-aa82-4379-9399-a38a8db99664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;t-body-home&quot;]/div[@class=&quot;fc-consent-root&quot;]/div[@class=&quot;fc-dialog-container&quot;]/div[@class=&quot;fc-dialog fc-choice-dialog&quot;]/div[@class=&quot;fc-footer-buttons-container&quot;]/div[@class=&quot;fc-footer-buttons&quot;]/button[@class=&quot;fc-button fc-cta-consent fc-primary-button&quot;]/p[@class=&quot;fc-button-label&quot;]</value>
      <webElementGuid>601aaece-eb85-46a6-95ea-ae9022cc1f78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/p</value>
      <webElementGuid>b7ae02f4-ec66-4d80-9920-6a587ed9e684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Consentir' or . = 'Consentir')]</value>
      <webElementGuid>e261dc21-80e9-4b4f-9347-853d3eaa2e1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
