<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_fa fa-times</name>
   <tag></tag>
   <elementGuidId>6d8aa024-25b7-4c03-84d3-92107126cf73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.pr-2.text-right > i.fa.fa-times</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//i[@type='button'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>dcc59881-70b1-420f-9295-0b4ae50d26ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>99d7355e-359f-40ce-a461-1c444c528a15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>22a6b30e-0f18-444f-929b-c01af1efd0e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-times</value>
      <webElementGuid>92cd439f-2cf0-440a-87fe-80fa248fd318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e664a027-b8e4-4fe4-9040-9ab4e03cb109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TinAdPopup&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered modal-dialog-scrollable modal-xl modal-adaptive&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;pr-2 text-right&quot;]/i[@class=&quot;fa fa-times&quot;]</value>
      <webElementGuid>6166b7e0-9150-48f8-9001-81ebf797c86a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//i[@type='button'])[5]</value>
      <webElementGuid>ce62a226-335a-4fc4-a8c9-7defc4c6ec3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TinAdPopup']/div/div/div/i</value>
      <webElementGuid>a60c71b9-a9b1-4c10-a258-ee5dba42747b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/i</value>
      <webElementGuid>9598d814-3f36-46bf-8be2-2cd2a57e4f2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@type = 'button']</value>
      <webElementGuid>33742bfa-492c-4bae-b32b-16cfbd546bc6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
