<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe378c8f7998fcc4abc9e1d3ba3ec45ff0</name>
   <tag></tag>
   <elementGuidId>126f3869-ef01-446a-8e0e-045e9f606d66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#378c8f7998fcc4abc9e1d3ba3ec45ff0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='378c8f7998fcc4abc9e1d3ba3ec45ff0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>76b03753-d960-4121-aa94-25e33c2bbed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>378c8f7998fcc4abc9e1d3ba3ec45ff0</value>
      <webElementGuid>c1807aa5-1b0c-4d29-92be-02e1490c957c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c1588788-f201-4211-81de-c6317cca5323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>58774ae4-7454-4ece-848a-ea539ce4fd02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>webPushIframe</value>
      <webElementGuid>f9734428-48ab-4a96-8d29-2c647bc75f05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>E-goi Webpush App</value>
      <webElementGuid>82b168d1-d250-44c0-a433-53a7ac404b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;378c8f7998fcc4abc9e1d3ba3ec45ff0&quot;)</value>
      <webElementGuid>c66e303f-a71c-40b6-94fa-50260d8a290e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='378c8f7998fcc4abc9e1d3ba3ec45ff0']</value>
      <webElementGuid>3549adcd-c68d-49f9-865f-ea980200c0a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe[3]</value>
      <webElementGuid>fee1b5ef-ac3c-41cd-a92c-b12e150b7930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = '378c8f7998fcc4abc9e1d3ba3ec45ff0' and @title = 'E-goi Webpush App']</value>
      <webElementGuid>f6417235-73fa-44d3-9d86-2be0784df76f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
