<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Benfica</name>
   <tag></tag>
   <elementGuidId>aec8c2b1-19a1-42dd-9d01-9c7fdb4ddb05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.section-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[4]/div[2]/div/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8d311130-8e7e-463f-9358-04d189d6f8bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>section-title</value>
      <webElementGuid>70744f12-9f35-45d6-bb13-610d4fcc483c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Benfica</value>
      <webElementGuid>30d92634-a126-418c-b246-834e9b5d8d1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;body-content&quot;]/div[@class=&quot;jg017-container component-root in-viewport&quot;]/div[@class=&quot;jg017-top-container&quot;]/div[@class=&quot;sk-container&quot;]/div[@class=&quot;sk-wrapper&quot;]/div[@class=&quot;sk-1&quot;]/div[@class=&quot;section-title-container&quot;]/div[@class=&quot;section-title&quot;]</value>
      <webElementGuid>347998a8-9acf-4539-a581-dcda30a19465</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[4]/div[2]/div/div/div/div/div/div</value>
      <webElementGuid>db7753ce-8f4e-41be-a777-c5c070d7a84d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div</value>
      <webElementGuid>502fb934-b0d1-4e0d-bae4-8ab4686bd6a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Benfica' or . = 'Benfica')]</value>
      <webElementGuid>12b264ac-513a-4aea-92b0-b42304088f52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
