<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Presidente_1</name>
   <tag></tag>
   <elementGuidId>ed5264b7-14dd-4146-b50a-ef107a403064</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#collapse200 > a.menu_m_accordion45</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='collapse200']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>83e0640f-19b0-469b-895b-975b0fae90a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Link Presidente</value>
      <webElementGuid>b4d19d3f-4e41-4a11-b5f2-c2e1dfbf75e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu_m_accordion45</value>
      <webElementGuid>9171e932-fbce-46bb-a775-c5dc59252dde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>b5576a5f-36d2-4e87-a9a4-d4e4b1db2dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/sites/PARXVL/Paginas/default.aspx</value>
      <webElementGuid>abbfa684-dafc-428a-a5e0-92b18ee39464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                        Presidente
                                                        </value>
      <webElementGuid>18b1f5d6-d0d2-46c8-b9e7-ef151037fed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapse200&quot;)/a[@class=&quot;menu_m_accordion45&quot;]</value>
      <webElementGuid>d00c2483-53ac-4da3-ba99-7905825037a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapse200']/a</value>
      <webElementGuid>c71aa6a1-e50d-4f07-aa0b-9fedefa02e3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Presidente')])[11]</value>
      <webElementGuid>218db2b4-b0c5-4a92-a8d0-95de33aeaf04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/sites/PARXVL/Paginas/default.aspx')])[2]</value>
      <webElementGuid>99b2b379-9943-41f1-87ca-60090b8012b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/a</value>
      <webElementGuid>3772cf5b-78d4-47f7-92af-ff7b039c098a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Link Presidente' and @href = '/sites/PARXVL/Paginas/default.aspx' and (text() = '
                                                        Presidente
                                                        ' or . = '
                                                        Presidente
                                                        ')]</value>
      <webElementGuid>dc72f777-f716-44ce-b885-945a7c0f6196</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
