<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Presidente</name>
   <tag></tag>
   <elementGuidId>24e2d0c1-bd40-4330-a7f3-b1e6d026b66c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accordion2 > div.panel.panel-default > a.menu_m_accordion70</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='accordionAction(2,200);']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>259aad1f-89df-4561-aaf5-6a2c76be4f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Link Presidente</value>
      <webElementGuid>441b630b-2bed-4c69-a713-1e6c24c578fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>4c4cfb36-78c5-4790-aaf7-67423f0b85b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu_m_accordion70</value>
      <webElementGuid>87cae684-dc3c-4719-82a9-dd6e6d9dec05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#collapse200</value>
      <webElementGuid>db459ef5-331c-416f-9db6-e57527dc7345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>dd741107-4152-461a-b764-dfbffa2742a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parent</name>
      <type>Main</type>
      <value>#accordion2</value>
      <webElementGuid>3dd4e9b0-ae0e-4da8-874c-a8aa379bb745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>accordionAction(2,200);</value>
      <webElementGuid>accf0a71-d142-4fa9-9c72-72dc0f116079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Presidente
                                            
                                        </value>
      <webElementGuid>82ab61ac-cac4-4d19-a52c-4494ac5c14d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordion2&quot;)/div[@class=&quot;panel panel-default&quot;]/a[@class=&quot;menu_m_accordion70&quot;]</value>
      <webElementGuid>ff644f23-8e37-465e-8930-f94f731a2879</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='accordionAction(2,200);']</value>
      <webElementGuid>1151a9a8-862f-4ff0-8455-726ecf469b9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordion2']/div/a</value>
      <webElementGuid>fe5fc1fe-1feb-4696-815b-aa79bd5c94c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Presidente')])[10]</value>
      <webElementGuid>5ef94d59-51c9-4b10-ab3f-5a2e0e0863c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#collapse200')]</value>
      <webElementGuid>1d653cbb-c25b-4823-b0c1-621527722485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a</value>
      <webElementGuid>4cce5472-7284-46e1-9f87-5acde28354c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Link Presidente' and @href = '#collapse200' and (text() = 'Presidente
                                            
                                        ' or . = 'Presidente
                                            
                                        ')]</value>
      <webElementGuid>c5134e94-aa3f-421a-bbf9-6295a0c5665c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
