<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>c9c2fe6e-181a-4f97-848c-72afa0e76c0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Início&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ctl53_anchorLogo']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0fba7c6c-948f-4e0e-8828-0ad2c482815b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/style library/AR/Images/navbarLogo.png</value>
      <webElementGuid>2e96bf85-f05a-455d-941c-605f68267986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Início</value>
      <webElementGuid>af46cff6-a885-4661-a36b-12cc0f6696aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ctl53_anchorLogo&quot;)/img[1]</value>
      <webElementGuid>4ed0f0a1-d522-40a7-a7ba-ed55330eaac5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ctl53_anchorLogo']/img</value>
      <webElementGuid>282fed15-bc52-4dac-98a0-ff091091ebe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Início']</value>
      <webElementGuid>86bb3e57-f319-4c6c-afb9-8cef4e0438cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>fd8fe0c1-a9ee-4b4f-b22e-e46a0bdb66d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/style library/AR/Images/navbarLogo.png' and @alt = 'Início']</value>
      <webElementGuid>ec0e17c7-add7-4dae-90c4-371d7c90e681</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
