<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>408042c8-0539-4608-9a54-3d3269c33dc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Menu&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menubutton']/button/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>06875a73-e73c-4738-80af-ffba309cc726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/style library/AR/Images/iconMenu.png</value>
      <webElementGuid>71f2d0f1-b328-49dd-9b64-98a4a017c8dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Menu</value>
      <webElementGuid>19504c29-a5e6-400b-a44c-700e289e3310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menubutton&quot;)/button[@class=&quot;navbar-toggle topicon hidden-lg&quot;]/img[1]</value>
      <webElementGuid>da30764f-f93e-4ce6-a519-0bd7e078ffab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menubutton']/button/img</value>
      <webElementGuid>bd1be104-200a-4783-8957-20d9c925798d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Menu']</value>
      <webElementGuid>4e590986-00ed-4a87-b3b6-21cfb50d2a8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button/img</value>
      <webElementGuid>5346d37c-fdf3-492e-bad0-041184295146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/style library/AR/Images/iconMenu.png' and @alt = 'Menu']</value>
      <webElementGuid>c012b335-92a2-4ac1-ab65-890cd5c6b39e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
