<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>d8b06ce2-8eaf-449b-a565-c6f54de1069f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;logo-jn-sem-texto&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/div/div[2]/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8103736a-5bcf-4c41-a568-5dfd728d77f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/logos/logo-jn-sem-texto.png</value>
      <webElementGuid>3ef3c884-63cf-450e-9727-4f18c6b9ded2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logo-jn-sem-texto</value>
      <webElementGuid>f54579ac-c53f-4ffe-8760-ac9893341546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>91</value>
      <webElementGuid>31939d52-f1af-491a-a0f6-9b45dca6500e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>76</value>
      <webElementGuid>39f65ff1-93b0-40a2-8926-11044c029be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;header-container&quot;]/div[@class=&quot;header&quot;]/div[@class=&quot;left&quot;]/div[@class=&quot;logo-jn&quot;]/a[@class=&quot;clean-link&quot;]/img[1]</value>
      <webElementGuid>6ceb8cbe-77db-4fdb-bb1f-a5444a37cf0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/div/div[2]/div/div/a/img</value>
      <webElementGuid>a16dea40-2a05-4540-986d-8e38ae6af446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='logo-jn-sem-texto']</value>
      <webElementGuid>7c6d7cfb-45cd-43cc-a591-866994261d29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/img</value>
      <webElementGuid>3bf9a98b-38dc-438b-8b5d-58ddd8d4f5d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/img/logos/logo-jn-sem-texto.png' and @alt = 'logo-jn-sem-texto']</value>
      <webElementGuid>b5622372-33ec-4575-8046-1339a8e99231</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
