<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sbado</name>
   <tag></tag>
   <elementGuidId>6600b043-2abb-4248-a18d-c7042ae8f716</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.logo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(@href, '/')])[42]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2c51daee-654f-4002-8157-6a7da014ad07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/</value>
      <webElementGuid>f815c157-474e-41d7-9be9-b4b738afaf56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>dd4d6544-0c93-465c-ae57-95b2340fd631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sábado</value>
      <webElementGuid>0e2dc3da-b46b-4c9a-8e90-abaeb1ee2e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wbo-id</name>
      <type>Main</type>
      <value>43</value>
      <webElementGuid>ba094013-0df4-4753-89a9-8470856753d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sábado</value>
      <webElementGuid>c80aeb01-e6f9-46cd-83cf-59c4d782087d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mastheadVisible&quot;]/header[@class=&quot;header&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;main_header&quot;]/div[@class=&quot;header_top&quot;]/a[@class=&quot;logo&quot;]</value>
      <webElementGuid>82811b81-429a-4d39-a120-f941ab1ad984</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/')])[42]</value>
      <webElementGuid>02f5a331-5307-4a0b-a349-8c3a772e90ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div[2]/div/div/a</value>
      <webElementGuid>686917ef-1275-438a-a495-615a86364b74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/' and @title = 'Sábado' and (text() = 'Sábado' or . = 'Sábado')]</value>
      <webElementGuid>1293786b-efac-4515-8366-96e9dc1c732b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
