<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>imgrptClassificacaoPais_imgLogo_0</name>
   <tag></tag>
   <elementGuidId>9e303a7c-1f55-426e-b90d-c636f361a51b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@id='rptClassificacaoPais_imgLogo_0'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5f627ed2-a89d-46b8-a8af-974ceca30324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rptClassificacaoPais_imgLogo_0</value>
      <webElementGuid>e2acc641-179a-4452-9ce6-6004bcafc241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Benfica - 29 pontos</value>
      <webElementGuid>4ea8f666-7692-43f9-a3a4-91f27b16b5c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>4ee1533f-4bf6-4d69-bfb5-fd2e4be76e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>bottom</value>
      <webElementGuid>e66b55d1-c46d-4f45-aa16-cf1004e3b7b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>97ea161f-9454-4225-af59-1a3680362980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://sportal365images.com/process/smp-images-production/assets/team/logo/450-Benfica-logo.png</value>
      <webElementGuid>03d1c7c8-8fb3-4dff-8964-29e41ef85e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corpo&quot;)/div[@class=&quot;homepage-container&quot;]/div[@class=&quot;livescore-bar-widget mb-15 clearfix&quot;]/div[@class=&quot;row mt-10&quot;]/section[@class=&quot;row-clubes pb-0&quot;]/section[@class=&quot;overflow-ini clearfix pb-0&quot;]/div[@class=&quot;col-md-12 opcoes&quot;]/div[@class=&quot;col-md-12 abola-seccao clubes&quot;]/div[@class=&quot;pull-left lista-clubes col-md-8 col-sm-7 col-xs-12 padding-0&quot;]/div[@class=&quot;lista-clubes linha-clubes scrollbar scrollbar-x&quot;]/div[@class=&quot;caixa semPadding clube&quot;]/a[1]/img[@id=&quot;rptClassificacaoPais_imgLogo_0&quot;]</value>
      <webElementGuid>f7a59a2b-6f54-49a7-9a90-0062be4a39b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//img[@id='rptClassificacaoPais_imgLogo_0'])[2]</value>
      <webElementGuid>b10d90c9-65a7-4c3b-ab00-5ea634257150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corpo']/div/div[4]/div/section/section/div/div/div[2]/div/div[4]/a/img</value>
      <webElementGuid>b500e23e-fb60-4506-80dd-86783fda3b2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='Benfica - 29 pontos']</value>
      <webElementGuid>76a82945-50eb-4099-bb09-f685510ee22c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a/img</value>
      <webElementGuid>5de7bcae-449a-4fd1-949a-b33b53795cd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'rptClassificacaoPais_imgLogo_0' and @title = 'Benfica - 29 pontos' and @src = 'https://sportal365images.com/process/smp-images-production/assets/team/logo/450-Benfica-logo.png']</value>
      <webElementGuid>c73ea287-d547-4230-8f16-8d3534ffcfe2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
