<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_botao fechar</name>
   <tag></tag>
   <elementGuidId>8fda4424-90bb-4111-a09b-cbc9b7cce89f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uyoracog</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='uyoracog']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9eed18f2-cb32-4562-aea9-403b9e52b504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>crea</name>
      <type>Main</type>
      <value>itolukem</value>
      <webElementGuid>06ca1b2f-6c89-4045-a1d6-1462de2297a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rnd</name>
      <type>Main</type>
      <value>sNiDBleFoPzt</value>
      <webElementGuid>9ef11922-e547-4d3f-aa54-22f35977e00d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>material-id</name>
      <type>Main</type>
      <value>449d67e9-aa79-4dea-9b7f-ed0162c623f8</value>
      <webElementGuid>56c8d49f-f868-43d8-8c36-4010dd1e70ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uyoracog</value>
      <webElementGuid>61c4e5b4-419d-4135-8f2d-0ab355aa73e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>v-align</name>
      <type>Main</type>
      <value>manual</value>
      <webElementGuid>a9ebb9fa-74b2-4548-8a0f-edd1290629a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1259c094-8e62-4361-8a21-24276e3e04da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>h-align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>f0905829-8770-4f7e-9bce-b238b4b3c362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>true-width</name>
      <type>Main</type>
      <value>34px</value>
      <webElementGuid>17544d48-4063-4474-a369-9f9f92bc9a57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>true-height</name>
      <type>Main</type>
      <value>28px</value>
      <webElementGuid>0cee0a6f-29fc-425a-8577-ec605b34a2f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scale</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ba95b695-e492-4458-b72b-0584ffdca118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lock-aspect-ratio</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>297900cb-b7fd-4542-bbaa-8cd795af4896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pivot</name>
      <type>Main</type>
      <value>50% 50%</value>
      <webElementGuid>3f75eb44-8e54-4d4a-a391-556810df0eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>botao fechar</value>
      <webElementGuid>ffc50d8e-9afe-4215-860d-2feb8492d422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>account</name>
      <type>Main</type>
      <value>6345f08022ed61d7ccf8c3ab</value>
      <webElementGuid>24895b40-0f51-45bf-aee6-4f2e5865ded1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>content-type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>29b14744-a1cc-4452-9c63-c8c42929d3be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uyoracog&quot;)</value>
      <webElementGuid>cb96eb05-90bf-4fe4-98ad-635610dc4c6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='uyoracog']</value>
      <webElementGuid>f45b6248-cca8-4ee2-9bcb-7eb5eceb4a20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vxl-background']/div[2]</value>
      <webElementGuid>847b4882-5490-48e4-a99c-aa52278e007d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//advoxel/div[5]/div[2]</value>
      <webElementGuid>b2c46065-a5ff-4c44-8d5e-58d7d9e3527a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'uyoracog' and @type = 'div' and @name = 'botao fechar']</value>
      <webElementGuid>39d23ab6-0a22-4aee-baab-453a048db2e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
