<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_masthead__branding__logo</name>
   <tag></tag>
   <elementGuidId>949f4244-dc46-4dc2-95d9-63dbde67ac18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.masthead__branding__logo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>2dd93aae-0e44-46dd-945c-635bf88bd476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masthead__branding__logo</value>
      <webElementGuid>1c330edb-60a1-4c3b-aef6-3977d71f3687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>14593909-4bd2-4402-b0a6-f07cfab212ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>3101e20c-1a74-4418-8ff5-599e7cda5ebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 56 59</value>
      <webElementGuid>2b44b0bb-3209-4cd5-8c9a-463151ad3519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>56</value>
      <webElementGuid>83a7da66-b5c7-4aa7-9f71-9c20786e55c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>59</value>
      <webElementGuid>48e28ae8-8b8c-4609-9f02-25d28022a409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;masthead&quot;)/div[@class=&quot;masthead--paint&quot;]/div[@class=&quot;new-container masthead__wrapper&quot;]/div[@class=&quot;masthead__container&quot;]/div[@class=&quot;masthead__main&quot;]/div[@class=&quot;masthead__branding&quot;]/h1[@class=&quot;masthead__branding__heading&quot;]/a[1]/svg[@class=&quot;masthead__branding__logo&quot;]</value>
      <webElementGuid>d1e7e686-c455-4643-8519-3beeceb7045c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
