<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_img-fluid</name>
   <tag></tag>
   <elementGuidId>fb426f76-f7f0-4b8e-b7ef-3b57f4ac3854</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.header-bottom > a.clean-link > img.img-fluid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/div[2]/div/div/div[2]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>46ed5c19-318c-42d2-aeac-90b43091f083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://asset.skoiy.com/ojonxcycnuapxiqs/h95m7avu0i7i.png?w=32&amp;h=32&amp;q=80</value>
      <webElementGuid>df1a89cd-2982-432a-99a0-c0435056a901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>c58e3913-6dd6-485c-aa46-77a85387c05f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>31932004-4b10-426f-9e77-20585ca132d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>9f147494-473f-4cec-b48a-93708b58a682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>37cdaea4-f44a-421b-84e4-39247a53d247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid</value>
      <webElementGuid>62a51702-cf86-4eaa-ab8f-c21ae022f805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;header-component&quot;]/div[@class=&quot;header-container&quot;]/div[@class=&quot;header&quot;]/div[@class=&quot;header-bottom&quot;]/a[@class=&quot;clean-link&quot;]/img[@class=&quot;img-fluid&quot;]</value>
      <webElementGuid>91bb9d7a-2ebc-4ca4-9817-7726db2f9b2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/div[2]/div/div/div[2]/a/img</value>
      <webElementGuid>9bf629ad-cbc6-4deb-b562-fa4bd868555d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='[object Object]']</value>
      <webElementGuid>a564b927-90a4-4574-a538-afd8603d867b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/img</value>
      <webElementGuid>84205f7d-272d-40d2-a533-80f7d04da140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://asset.skoiy.com/ojonxcycnuapxiqs/h95m7avu0i7i.png?w=32&amp;h=32&amp;q=80' and @alt = '[object Object]']</value>
      <webElementGuid>2e28d3a0-7306-476b-8adf-f931911d473a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
