<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>08a94f1c-2f34-4bd9-b3e2-54212c5a8987</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#adCloseButton1 > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='adCloseButton1']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5b5b6e53-8832-43bc-bb6e-7b0121874ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://zap.aeiou.pt/interst/avancar1.png</value>
      <webElementGuid>b9afce1e-8a71-4386-a939-af8a6f62630c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;adCloseButton1&quot;)/img[1]</value>
      <webElementGuid>124e83b4-015d-46af-9b0e-085e4fc80469</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='adCloseButton1']/img</value>
      <webElementGuid>0e17b809-f4cb-4282-9482-3ba98e444392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://zap.aeiou.pt/interst/avancar1.png')]</value>
      <webElementGuid>a413238e-b6f5-4882-9a35-460126fdf8ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/img</value>
      <webElementGuid>a60da650-d89f-4b10-bec4-fa9983b6216a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://zap.aeiou.pt/interst/avancar1.png']</value>
      <webElementGuid>498ff76a-d4cd-497c-9c00-1b6a9f6ea4dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
