<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_main-img-logo</name>
   <tag></tag>
   <elementGuidId>0dc49540-f89d-4247-8892-97dff55fb25a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.main-img-logo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='site-logo']/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a2427ffd-955c-42ab-9cf8-b3ac57397450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://zap.aeiou.pt/wp-content/uploads/2021/10/59cd8e76cde1067d8950e8bf04b673eb.png</value>
      <webElementGuid>12bbd325-dd8b-4b1d-8431-aefaf36ccca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Logo</value>
      <webElementGuid>83c51547-1d7c-48fd-9184-46146206cd26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main-img-logo</value>
      <webElementGuid>9e3974f8-cda9-499b-8456-769ad8893aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-logo&quot;)/a[1]/img[@class=&quot;main-img-logo&quot;]</value>
      <webElementGuid>777ba330-4223-4949-9d35-c3cddea87f11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h2[@id='site-logo']/a/img</value>
      <webElementGuid>fba9b24e-195e-45b1-ab1b-3b5e9a454ab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Logo']</value>
      <webElementGuid>3c97a7c1-298c-45e6-b1cf-0a51e573777b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>a74ce92a-3f0b-47a2-8117-e8a2f1722d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://zap.aeiou.pt/wp-content/uploads/2021/10/59cd8e76cde1067d8950e8bf04b673eb.png' and @alt = 'Logo']</value>
      <webElementGuid>c64f8006-1913-4333-b9b8-bb896dfc79c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
