<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Benfica</name>
   <tag></tag>
   <elementGuidId>ea1fe907-6fbc-421e-9468-b7539cd9166c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#body_MenuTopoGenerico_lblNomeSeccao</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='body_MenuTopoGenerico_lblNomeSeccao']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a8f1b7aa-cd09-4b60-a9d9-1489941c4d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>body_MenuTopoGenerico_lblNomeSeccao</value>
      <webElementGuid>e22c9558-f26d-47f4-b174-dfa18d318353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Benfica</value>
      <webElementGuid>2b9e1c5a-66bb-4328-8d8e-4058e91add58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body_MenuTopoGenerico_lblNomeSeccao&quot;)</value>
      <webElementGuid>5b20ae04-f2de-4dac-b6be-0b81145a05a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='body_MenuTopoGenerico_lblNomeSeccao']</value>
      <webElementGuid>fe420ad2-5062-4a67-a40a-b0e5f05eb746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='body_MenuTopoSeccoes_lblNomeSeccao']/h1/span</value>
      <webElementGuid>e5a9bf96-e7e2-4624-90bc-592c73b7adf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BENFICA'])[1]/following::span[2]</value>
      <webElementGuid>30f7202f-25a7-4520-a4a0-babaf079e2e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LIGA'])[1]/following::span[3]</value>
      <webElementGuid>8c1e3e6b-f17e-4859-9992-c902fe4a698b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notícias'])[2]/preceding::span[2]</value>
      <webElementGuid>c5bdbbb9-536a-4e92-9c78-c8f4e6c1f622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Videos'])[2]/preceding::span[2]</value>
      <webElementGuid>adb28762-5601-4a90-a05e-363248f52050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/span</value>
      <webElementGuid>3e23c35a-74d3-407b-9d8c-79214d60e56a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'body_MenuTopoGenerico_lblNomeSeccao' and (text() = 'Benfica' or . = 'Benfica')]</value>
      <webElementGuid>aad43031-1fca-4e47-b1a0-48ae10bc80e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
