<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Benfica</name>
   <tag></tag>
   <elementGuidId>ea1fe907-6fbc-421e-9468-b7539cd9166c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#body_MenuTopoGenerico_lblNomeSeccao</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='body_MenuTopoGenerico_lblNomeSeccao']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dc5dec19-b38d-47af-aa30-ec37c280ef1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>body_MenuTopoGenerico_lblNomeSeccao</value>
      <webElementGuid>01ee280e-4f88-4824-8b90-ef915a09971d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Benfica</value>
      <webElementGuid>fc4d09da-b8df-448f-814d-2225c610334d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body_MenuTopoGenerico_lblNomeSeccao&quot;)</value>
      <webElementGuid>212fcac4-a01f-4367-a9ad-3cda06ab5cf7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='body_MenuTopoGenerico_lblNomeSeccao']</value>
      <webElementGuid>d5947a4f-9ef7-4498-9922-cfe1c1d50747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='body_MenuTopoSeccoes_lblNomeSeccao']/h1/span</value>
      <webElementGuid>1ab89bc3-6008-4aed-9d29-380cde972c62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/span</value>
      <webElementGuid>6d391549-3a1b-4006-a8ba-2f80379d7766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'body_MenuTopoGenerico_lblNomeSeccao' and (text() = 'Benfica' or . = 'Benfica')]</value>
      <webElementGuid>7a293802-545a-4ced-9f16-12d6ba492082</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
