<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Primeiro-Ministro</name>
   <tag></tag>
   <elementGuidId>7aabe811-ee56-4ace-b806-66d8cc87a929</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.tree-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='nav-menu']/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a4747c7f-eefa-4460-88a6-596f32e9b1e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tree-text</value>
      <webElementGuid>3802f009-0eb6-4ac1-9f94-dfda922c005a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>pt/gc23/primeiro-ministro</value>
      <webElementGuid>e6528a2e-aace-448e-ace2-7f6fb4acbe6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Primeiro-Ministro</value>
      <webElementGuid>fdee3a30-ccb6-4066-8470-c2be52390962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-menu&quot;)/ul[@class=&quot;tree-level1&quot;]/li[@class=&quot;hover&quot;]/a[@class=&quot;tree-text&quot;]</value>
      <webElementGuid>1bef205f-9803-46a3-bf47-f7b398936439</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='nav-menu']/ul/li/a</value>
      <webElementGuid>371507ca-4154-4be1-b6ff-c976e1bbc706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Primeiro-Ministro')]</value>
      <webElementGuid>b826bdca-88ea-4dda-a024-d3192cc297a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'pt/gc23/primeiro-ministro')]</value>
      <webElementGuid>63892267-8971-4bce-8d62-2ec42443d643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li/a</value>
      <webElementGuid>b5ddb731-a7a0-4f4b-a368-04f45d438d62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'pt/gc23/primeiro-ministro' and (text() = 'Primeiro-Ministro' or . = 'Primeiro-Ministro')]</value>
      <webElementGuid>e70089aa-38c2-4ff3-9a87-ef2611bd9f80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
