<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonnavbar-toggle</name>
   <tag></tag>
   <elementGuidId>3ab42541-d573-46bd-925a-1d21bfaff746</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#navbar-toggle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='navbar-toggle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>aaea23c2-d0ba-4fbe-bb01-637bf5a28f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2bca9648-0b21-42f0-8576-4d6294aea411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>navbar-toggle</value>
      <webElementGuid>46490438-1518-4c16-91ff-ecedf8f2c3fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navbar-toggle collapsed</value>
      <webElementGuid>e30e3537-1b45-48af-aa51-a77b48489128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c30708eb-6685-43dd-8718-ff2ffe1b87c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar-toggle&quot;)</value>
      <webElementGuid>0ff5ff0e-1920-495b-bdf6-41d135fac2ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='navbar-toggle']</value>
      <webElementGuid>dc3ca1b5-a557-48fd-8a40-36d67034e174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='masterIcons']/button</value>
      <webElementGuid>567474e8-b5f4-4b1a-be95-d304ebec0dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>d16c5b5d-797e-4f2c-b6bb-1c8788100d4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'navbar-toggle']</value>
      <webElementGuid>1d6c7675-ba2a-46c4-8b52-67a599bae346</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
