<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Benfica</name>
   <tag></tag>
   <elementGuidId>5e73983d-f964-4005-8844-36958b4e0805</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.benfica > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Benfica')])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>80ee8442-0693-4fed-89e0-0093da8e2ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/futebol/futebol-nacional/liga-betclic/benfica?ref=Benfica_Menu</value>
      <webElementGuid>c3f85bc9-6f6a-4517-8e22-f74b04deeb84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics-category</name>
      <type>Main</type>
      <value>Menu_Menu</value>
      <webElementGuid>005c3d25-c58e-4db1-8345-f989eb59a002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics-action</name>
      <type>Main</type>
      <value>titulo</value>
      <webElementGuid>cfd172e9-0e4c-4a9d-ab34-0f4f4d9bbd84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics-label</name>
      <type>Main</type>
      <value>/futebol/futebol-nacional/liga-betclic/benfica?ref=Benfica_Menu</value>
      <webElementGuid>764b9d4f-b8d1-4538-84d8-095dfde895b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wbo-id</name>
      <type>Main</type>
      <value>241</value>
      <webElementGuid>54260486-6d3b-49a4-af0b-42c9f6ff6afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Benfica</value>
      <webElementGuid>e6714a60-e97f-431f-b713-7b514ba33bba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;header_utils&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;d-flex flex-column flex-lg-row&quot;]/div[@class=&quot;centro&quot;]/div[@class=&quot;menuTop&quot;]/h2[@class=&quot;benfica&quot;]/a[1]</value>
      <webElementGuid>f8b872fe-3a17-4ba5-81fa-34429374106e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Benfica')])[7]</value>
      <webElementGuid>9bf282e2-a270-4d41-8176-6749a50c543d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UDL Match Day'])[1]/following::a[1]</value>
      <webElementGuid>e058d15f-4870-49d3-868e-88293046e6ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publicidade'])[1]/following::a[2]</value>
      <webElementGuid>c1960265-8929-4964-996b-2c17aabb9738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Classificação'])[4]/preceding::a[1]</value>
      <webElementGuid>c6d109be-877d-4878-a3a6-4102a48f5baa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resumos'])[2]/preceding::a[2]</value>
      <webElementGuid>4d1fb326-e5a9-4587-8fd5-7ced20046d5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/futebol/futebol-nacional/liga-betclic/benfica?ref=Benfica_Menu')]</value>
      <webElementGuid>0d01c6c0-a6b0-4709-a523-2596d9500b7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2/a</value>
      <webElementGuid>64df6857-0f3a-4e01-89ad-34b0817d1a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/futebol/futebol-nacional/liga-betclic/benfica?ref=Benfica_Menu' and (text() = 'Benfica' or . = 'Benfica')]</value>
      <webElementGuid>e1fb0abc-9676-4ae2-bd2d-090e4ea0dcb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
