<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Benfica</name>
   <tag></tag>
   <elementGuidId>5e73983d-f964-4005-8844-36958b4e0805</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Benfica')])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7227414c-c69a-4516-8697-dcb18fdd6231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/futebol/futebol-nacional/liga-betclic/benfica?ref=Benfica_Menu</value>
      <webElementGuid>8d4107eb-dd8c-4677-af0b-4a98bf36b44f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics-category</name>
      <type>Main</type>
      <value>Menu_Menu</value>
      <webElementGuid>878bb3f0-0656-4ac0-b956-e60598d46e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics-action</name>
      <type>Main</type>
      <value>titulo</value>
      <webElementGuid>a0b336d4-6117-413f-9ed0-c90f8fa5247d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics-label</name>
      <type>Main</type>
      <value>/futebol/futebol-nacional/liga-betclic/benfica?ref=Benfica_Menu</value>
      <webElementGuid>d80e5a8f-b1f6-4833-bbaf-ba1bf25efbfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wbo-id</name>
      <type>Main</type>
      <value>239</value>
      <webElementGuid>93a8610e-10d9-4dba-bb3f-3bbedaf1540f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Benfica</value>
      <webElementGuid>1b584bc0-83e5-45f0-97ce-a0fb626debeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;header_utils&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;d-flex flex-column flex-lg-row&quot;]/div[@class=&quot;centro&quot;]/div[@class=&quot;menuTop&quot;]/h2[@class=&quot;benfica&quot;]/a[1]</value>
      <webElementGuid>29c21df2-9bc2-4d18-8733-a1c6e3777a32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Benfica')])[7]</value>
      <webElementGuid>60faff40-56ec-4c96-b620-061a6531f927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/futebol/futebol-nacional/liga-betclic/benfica?ref=Benfica_Menu')]</value>
      <webElementGuid>c2e60023-183a-4839-a4f3-c0e8108b44d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2/a</value>
      <webElementGuid>9489dd2b-69cf-4eea-9f3b-5380eae461d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/futebol/futebol-nacional/liga-betclic/benfica?ref=Benfica_Menu' and (text() = 'Benfica' or . = 'Benfica')]</value>
      <webElementGuid>14d8318d-61f3-4842-93f9-80d06be13922</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
