<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Benfica</name>
   <tag></tag>
   <elementGuidId>4c6ff229-3341-4ae6-9d73-086683a9d92a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>eecb3949-ea3b-4081-bd0b-240630358420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>benfica </value>
      <webElementGuid>58ab009c-071e-44b0-b3a7-89b61272d640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Benfica</value>
      <webElementGuid>83f8fcc3-6a71-4bfd-ad59-2e9043e29741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;header_utils&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;d-flex flex-column flex-lg-row&quot;]/div[@class=&quot;centro&quot;]/div[@class=&quot;menuTop&quot;]/h2[@class=&quot;benfica&quot;]</value>
      <webElementGuid>f8c2a8c8-c8fd-411d-abb6-39e444cdd68f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>e641f84b-b956-4fc6-b95b-bd3cbf73c36d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Benfica' or . = 'Benfica')]</value>
      <webElementGuid>e9c4fb55-e092-4a6f-89d9-ae1de5aff375</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
