<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_img-fluid</name>
   <tag></tag>
   <elementGuidId>c7bfe507-4b32-42ab-991a-5ebf9e5a4f48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mb-0 > img.img-fluid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/div/div/div/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ce71a861-26eb-4456-b3ca-f94c86ff97f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/media/byhcxh4p/p_horizontal_pt.svg</value>
      <webElementGuid>bdf8ad65-c92f-4385-b5ba-3b99d6ae4ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Secretaria-Geral da Presidência do Conselho de Ministros</value>
      <webElementGuid>911fbafe-a061-47d3-8f59-87c48cbab79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>84edfa95-eddc-4c92-9738-95174253f81d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>342</value>
      <webElementGuid>e4f29009-a01e-48f1-b1e9-013b0e80c481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid</value>
      <webElementGuid>bf1c84c2-4ddc-456e-93e7-12b0f7e3cc04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;subheader d-lg-block d-none&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row justify-content-between&quot;]/div[@class=&quot;col-lg-4&quot;]/div[@class=&quot;logo&quot;]/div[@class=&quot;mb-0&quot;]/img[@class=&quot;img-fluid&quot;]</value>
      <webElementGuid>4fd2011d-28c8-4616-91d7-3d647c5fff85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/div/div/div/div/div/div/img</value>
      <webElementGuid>81dd8fa2-816f-4713-b73d-33273752f760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Secretaria-Geral da Presidência do Conselho de Ministros'])[2]</value>
      <webElementGuid>81f7dcf6-bacc-414b-b2a0-1d14ef65cf30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>ca7f3282-39d8-418b-a94d-83063b03f5b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/media/byhcxh4p/p_horizontal_pt.svg' and @alt = 'Secretaria-Geral da Presidência do Conselho de Ministros']</value>
      <webElementGuid>03185eb5-338f-49d4-91aa-d2b349a8c5f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
